site_name: Doc perso
theme:
  name: material
  logo: assets/lemur.jpg
  font:
    text: Inter
    code: Fira Code
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: amber

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
    # Add features you want. `content.code.annotations` is specifically for code blocks.
    # It's not the one for general text annotations/tooltips.
    # - navigation.tabs
    # - toc.integrate

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details      # <--- Keep this enabled
  - pymdownx.superfences  # <--- Keep this enabled
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  # No material.extensions.annotations here!
  #- pymdownx.snippets:
  #    auto_append:
  #      - includes/abbreviations.md

nav:
  - Home: index.md
  - Pattern: pattern-fr.md
  - Cheat Sheet: cheat_sheet.md
  - Other Tests: test.md