site_name: TFFFS
theme:
  name: material
  logo: assets/lemur.png
  font:
    text: Inter
    code: Fira Code
  icon:
    annotation: material/information
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: amber

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    #- toc.integrate
    - content.code.annotate
    - content.code.copy
extra_css:
  - styles/extra.css # actually located in docs/styles/
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details      
  - pymdownx.superfences  
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  #- pymdownx.snippets:
  #    auto_append:
  #      - includes/abbreviations.md

nav:
  - Home: index.md
  - Home Server Setup:
    - Intro: homeserver/index.md
    - SSH: homeserver/ssh.md
    - Samba: homeserver/samba.md
  - Helpers:
    - Pattern: pattern-fr.md
    - Cheat Sheet: cheat_sheet.md
    - Other Tests: test.md