site_name: Doc perso
theme:
  name: material
  logo: assets/lemur.jpg
  font:
    text: Inter
    code: Fira Code
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: amber

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite

nav:
  - Home: index.md
  - Pattern: pattern-fr.md
  - Cheat Sheet: cheat_sheet.md